'use client';

import { useRef, useState } from 'react';
import { useChatStore } from '../store/useChatStore';
import { toPng } from 'html-to-image';
import download from 'downloadjs';
import { motion } from 'framer-motion';
import { Download, RefreshCw } from 'lucide-react';
import { Button } from '../../components/ui/button';


export default function ChatWrapped({
  data,
  vibe,
}: {
  data: any;
  vibe: any;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const [loading, setLoading] = useState(false);
  const { setMessages } = useChatStore();

  const topChatter = data.authors.reduce(
    (a: string, b: string) =>
      data.stats[a].count > data.stats[b].count ? a : b
  );

  const handleExport = async () => {
    if (!ref.current) return;
    setLoading(true);

    try {
      const dataUrl = await toPng(ref.current, {
        cacheBust: true,
        pixelRatio: 2,
      });
      download(dataUrl, 'chat-vibe-wrapped.png');
    } catch (err) {
      console.error('Export failed', err);
    }

    setLoading(false);
  };

  return (
    <div className="flex flex-col items-center gap-6 pb-20">
      <motion.div
        initial={{ scale: 0.9, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        className="relative"
      >
        <div
          ref={ref}
          className="w-[375px] h-[667px] bg-black text-white p-8 flex flex-col justify-between border border-zinc-800 rounded-3xl shadow-2xl"
          style={{
            backgroundImage:
              'radial-gradient(circle at 50% 0%, #22c55e33 0%, #000000 70%)',
          }}
        >
          {/* Header */}
          <div className="flex justify-between items-center">
            <h1 className="font-mono text-sm tracking-widest text-green-500">
              CHAT VIBE '26
            </h1>
            <span>🤖</span>
          </div>

          {/* Main */}
          <div className="space-y-8">
            <div>
              <p className="text-zinc-500 text-sm uppercase">
                Top Yap Machine
              </p>
              <h2 className="text-4xl font-bold text-green-400">
                {topChatter}
              </h2>
              <p className="text-zinc-400">
                Sent{' '}
                <span className="text-white font-bold">
                  {data.stats[topChatter].count}
                </span>{' '}
                messages
              </p>
            </div>

            <div className="p-4 bg-zinc-900/50 rounded-xl border border-white/10">
              <p className="text-zinc-500 text-xs uppercase mb-2">
                The Vibe Check
              </p>
              <p className="text-lg italic">
                "{vibe.roast}"
              </p>
            </div>

            <div className="grid grid-cols-2 gap-4">
              <div className="bg-zinc-900/50 p-3 rounded-lg">
                <p className="text-zinc-500 text-xs">
                  Simp Level
                </p>
                <p className="text-2xl font-bold text-purple-400">
                  {vibe.simpLevel}%
                </p>
              </div>
              <div className="bg-zinc-900/50 p-3 rounded-lg">
                <p className="text-zinc-500 text-xs">
                  Most Interested
                </p>
                <p className="text-lg font-bold">
                  {vibe.interestedParty}
                </p>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="text-center text-xs text-zinc-600">
            GENERATED BY CHATVIBE AI
          </div>
        </div>
      </motion.div>

      {/* Controls */}
      <div className="flex gap-4">
        <Button
          onClick={handleExport}
          disabled={loading}
          variant="secondary"
        >
          <Download className="w-4 h-4 mr-2" />
          {loading ? 'Exporting...' : 'Save Image'}
        </Button>

        <Button
          variant="outline"
          onClick={() => setMessages([])}
          className="text-red-500"
        >
          <RefreshCw className="w-4 h-4 mr-2" />
          Start Over
        </Button>
      </div>
    </div>
  );
}
